import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { Activity, AlertTriangle, BarChart3, Clock3, Database, KeyRound, Network, RefreshCw, Route, TrendingUp } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, DashboardBreakdown, DashboardSnapshot, ModelTimeBucket } from "../lib/api";
import { PageHeader } from "../App";
import { useI18n } from "../lib/i18nContext";

type Range = "1h" | "24h" | "7d" | "30d"; type Tab = "models" | "consumers" | "flow"; type Metric = "requests" | "tokens";
const RANGES: Range[] = ["1h", "24h", "7d", "30d"]; const COLORS = ["#60a5fa", "#34d399", "#fbbf24", "#f87171", "#a78bfa", "#22d3ee", "#fb7185", "#a3e635"];
const format = (n: number) => new Intl.NumberFormat().format(Math.round(n));
const success = (r: number, e: number) => r ? `${((1 - e / r) * 100).toFixed(1)}%` : "0.0%";

function Empty() { const { t } = useI18n(); return <div className="analytics-empty"><Database size={24} />{t.analytics.noData}</div>; }
function MetricCard({ icon: Icon, label, value, detail }: { icon: typeof Activity; label: string; value: string; detail: string }) { return <div className="metric-card analytics-metric"><div className="metric-card-top"><span className="metric-label">{label}</span><Icon size={16} /></div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div></div>; }
function Stacked({ buckets, series, metric }: { buckets: DashboardSnapshot["time_series"]; series: ModelTimeBucket[]; metric: Metric }) {
  const names = useMemo(() => [...new Set(series.map(x => x.model))], [series]); const rows = useMemo(() => buckets.map(bucket => { const row: Record<string, string | number> = { label: bucket.label }; names.forEach(name => row[name] = series.find(x => x.label === bucket.label && x.model === name)?.[metric] ?? 0); return row; }), [buckets, names, metric, series]);
  return series.length ? <ResponsiveContainer width="100%" height={300}><BarChart data={rows} margin={{ top: 8, right: 8, left: -16 }}><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip />{names.map((name, i) => <Bar key={name} dataKey={name} stackId="total" fill={COLORS[i % COLORS.length]} />)}</BarChart></ResponsiveContainer> : <Empty />;
}
function Trend({ rows }: { rows: DashboardSnapshot["time_series"] }) { return rows.length ? <ResponsiveContainer width="100%" height={250}><AreaChart data={rows} margin={{ top: 8, right: 8, left: -16 }}><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Area type="monotone" dataKey="requests" stroke="#60a5fa" fill="#60a5fa" fillOpacity={.18} strokeWidth={2} /></AreaChart></ResponsiveContainer> : <Empty />; }
function Distribution({ rows }: { rows: DashboardBreakdown[] }) { return rows.length ? <div className="analytics-distribution"><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={rows} dataKey="requests" nameKey="name" innerRadius={54} outerRadius={94}>{rows.map((row, i) => <Cell key={row.name} fill={COLORS[i % COLORS.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="analytics-legend">{rows.slice(0, 8).map((row, i) => <div key={row.name}><span style={{ background: COLORS[i % COLORS.length] }} />{row.name}<b>{format(row.requests)}</b></div>)}</div></div> : <Empty />; }

export default function AnalyticsPage() {
  const { t } = useI18n(); const navigate = useNavigate(); const [range, setRange] = useState<Range>(() => (localStorage.getItem("oxygenrouter.analytics.range") as Range) || "24h"); const [tab, setTab] = useState<Tab>("models"); const [metric, setMetric] = useState<Metric>("requests"); const [filter, setFilter] = useState("");
  useEffect(() => localStorage.setItem("oxygenrouter.analytics.range", range), [range]);
  const dashboard = useQuery({ queryKey: ["analytics", range], queryFn: () => api.dashboard.get(range), refetchInterval: 15000 }); const flow = useQuery({ queryKey: ["analytics-flow", range], queryFn: () => api.analytics.flow(range), refetchInterval: 15000 }); const data = dashboard.data;
  if (dashboard.isLoading) return <div className="page-fade-enter"><PageHeader title={t.analytics.title} description={t.analytics.description} /><div className="metric-grid analytics-metric-grid">{[1, 2, 3, 4, 5].map(x => <div className="metric-card" key={x}><div className="skeleton h-3 w-16" /><div className="skeleton h-6 w-24 mt-4" /></div>)}</div></div>;
  if (dashboard.isError || !data) return <div className="page-fade-enter"><PageHeader title={t.analytics.title} description={t.analytics.description} /><div className="error-banner"><AlertTriangle size={16} />{t.analytics.loadError}<button className="btn-outlined" onClick={() => dashboard.refetch()}>{t.analytics.retry}</button></div></div>;
  const minutes = Math.max((new Date(data.range_end).getTime() - new Date(data.range_start).getTime()) / 60000, 1); const links = (flow.data?.links ?? []).filter(link => `${link.source} ${link.target}`.toLowerCase().includes(filter.toLowerCase()));
  return <div className="page-fade-enter analytics-page"><PageHeader title={t.analytics.title} description={t.analytics.description} action={<button className="icon-button analytics-refresh" title={t.common.refresh} onClick={() => { dashboard.refetch(); flow.refetch(); }}><RefreshCw size={16} /></button>} />
    <div className="analytics-controls"><div className="analytics-tabs">{([["models", t.analytics.tabModel], ["consumers", t.analytics.tabConsumers], ["flow", t.analytics.tabFlow]] as [Tab, string][]).map(([id, label]) => <button key={id} className={`analytics-tab ${tab === id ? "is-active" : ""}`} onClick={() => setTab(id)}>{label}</button>)}</div><div className="analytics-range">{RANGES.map(value => <button key={value} className={range === value ? "is-active" : ""} onClick={() => setRange(value)}>{value}</button>)}</div></div>
    <div className="analytics-status"><Clock3 size={13} />{t.analytics.updated} {new Date(dashboard.dataUpdatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}. {t.analytics.autoRefresh}</div>
    {tab === "models" && <><div className="metric-grid analytics-metric-grid"><MetricCard icon={Activity} label={t.analytics.totalRequests} value={format(data.total_requests)} detail={t.analytics.requests} /><MetricCard icon={Database} label={t.analytics.totalTokens} value={format(data.total_tokens)} detail={t.analytics.tokens} /><MetricCard icon={TrendingUp} label={t.analytics.avgRPM} value={(data.total_requests / minutes).toFixed(2)} detail={t.analytics.statRPM} /><MetricCard icon={BarChart3} label={t.analytics.avgTPM} value={format(data.total_tokens / minutes)} detail={t.analytics.statTPM} /><MetricCard icon={Route} label={t.analytics.successRate} value={`${data.success_rate.toFixed(1)}%`} detail={`${format(data.successful_requests)} / ${format(data.total_requests)}`} /></div>
      <section className="dashboard-section"><div className="section-heading"><h2>{t.analytics.modelUsage}</h2><div className="analytics-switch"><button className={metric === "requests" ? "is-active" : ""} onClick={() => setMetric("requests")}>{t.analytics.requests}</button><button className={metric === "tokens" ? "is-active" : ""} onClick={() => setMetric("tokens")}>{t.analytics.tokens}</button></div></div><div className="analytics-chart"><Stacked buckets={data.time_series} series={data.model_time_series} metric={metric} /></div></section>
      <div className="analytics-two-column"><section className="dashboard-section"><div className="section-heading"><h2>{t.analytics.callTrend}</h2></div><div className="analytics-chart"><Trend rows={data.time_series} /></div></section><section className="dashboard-section"><div className="section-heading"><h2>{t.analytics.distribution}</h2></div><Distribution rows={data.model_breakdown} /></section></div>
      <section className="dashboard-section"><div className="section-heading"><h2>{t.analytics.health}</h2><span className="section-meta">{t.analytics.rankings}</span></div><div className="analytics-table-wrap"><table className="analytics-table"><thead><tr><th>{t.analytics.model}</th><th>{t.analytics.requests}</th><th>{t.analytics.successRate}</th><th>{t.analytics.avgLatency}</th><th>{t.analytics.tokens}</th></tr></thead><tbody>{data.model_breakdown.map(row => <tr key={row.name} onClick={() => navigate(`/ui/logs?model=${encodeURIComponent(row.name)}`)}><td>{row.name}</td><td>{format(row.requests)}</td><td>{success(row.requests, row.errors)}</td><td>{format(row.average_latency_ms)} {t.analytics.ms}</td><td>{format(row.tokens)}</td></tr>)}</tbody></table></div></section></>}
    {tab === "consumers" && <div className="analytics-two-column"><section className="dashboard-section"><div className="section-heading"><h2>{t.analytics.consumerUsage}</h2></div><div className="analytics-ranking">{data.api_key_breakdown.length ? data.api_key_breakdown.map(row => <button key={row.name} onClick={() => navigate(`/ui/logs?key=${encodeURIComponent(row.name)}`)}><KeyRound size={15} /><span>{row.name}</span><b>{format(row.requests)}</b><small>{success(row.requests, row.errors)} · {format(row.average_latency_ms)} {t.analytics.ms}</small></button>) : <Empty />}</div></section><section className="dashboard-section"><div className="section-heading"><h2>{t.analytics.consumerTrend}</h2></div><div className="analytics-chart"><Stacked buckets={data.time_series} series={data.api_key_time_series} metric={metric} /></div></section></div>}
    {tab === "flow" && <section className="dashboard-section"><div className="section-heading"><div><h2>{t.analytics.flowTitle}</h2><span className="section-meta">{metric === "requests" ? t.analytics.flowRequests : t.analytics.flowTokens}</span></div><label className="analytics-flow-filter"><Network size={14} /><input value={filter} onChange={e => setFilter(e.target.value)} placeholder={t.analytics.flowFilter} /></label></div><div className="analytics-flow"><div className="analytics-flow-column"><b>{t.analytics.apiKey}</b></div><div className="analytics-flow-column"><b>{t.analytics.model}</b></div><div className="analytics-flow-column"><b>{t.nav.channels}</b></div>{links.length ? links.map(link => <div className="analytics-flow-row" key={`${link.source}-${link.target}`}><span>{link.source.replace(/^[^:]+:/, "")}</span><Route size={16} /><span>{link.target.replace(/^[^:]+:/, "")}</span><b>{format(metric === "requests" ? link.request_count : link.tokens)}</b></div>) : <div className="analytics-flow-empty">{flow.isError ? t.analytics.loadError : t.analytics.noData}</div>}</div></section>}
  </div>;
}
