import React from "react";
import { Link, useNavigate } from "react-router-dom";
import Button from "../components/ui/Button";
import Input from "../components/ui/Input";
import { useAuth } from "../lib/auth";
import { useToast } from "../lib/toast";

export default function AuthPage({ mode }: { mode: "sign-in" | "sign-up" }) {
  const signUp = mode === "sign-up"; const navigate = useNavigate(); const { login, register } = useAuth(); const toast = useToast();
  const [values, setValues] = React.useState({ username: "", email: "", password: "" }); const [pending, setPending] = React.useState(false); const [error, setError] = React.useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); if (!values.username || !values.password || (signUp && !values.email)) { setError("Complete all required fields."); return; } if (values.password.length < 8) { setError("Password must be at least 8 characters."); return; } setPending(true); try { if (signUp) { await register(values.username, values.email, values.password); toast.success("Account created", "Sign in to continue."); navigate("/ui/sign-in"); } else { await login(values.username, values.password); toast.success("Signed in"); navigate("/ui/overview"); } } catch (err) { const message = err instanceof Error ? err.message : "Request failed"; setError(message); toast.error(signUp ? "Registration failed" : "Sign-in failed", message); } finally { setPending(false); } };
  return <div className="auth-page"><main className="auth-panel"><div className="auth-brand"><span className="brand-mark">O2</span><span>OxygenRouter</span></div><div className="auth-tabs"><Link className={!signUp ? "is-active" : ""} to="/ui/sign-in">Sign in</Link><Link className={signUp ? "is-active" : ""} to="/ui/sign-up">Create account</Link></div><h1>{signUp ? "Create your workspace account" : "Sign in to your workspace"}</h1><p>{signUp ? "Use a short, recognizable username for your team." : "Use your OxygenRouter account to manage billing."}</p><form onSubmit={submit} className="auth-form" noValidate>{error && <div className="error-banner" role="alert">{error}</div>}<Input label="Username" autoComplete="username" value={values.username} onChange={(e) => setValues({ ...values, username: e.target.value })} required autoFocus />{signUp && <Input label="Email" type="email" autoComplete="email" value={values.email} onChange={(e) => setValues({ ...values, email: e.target.value })} required />}<Input label="Password" type="password" autoComplete={signUp ? "new-password" : "current-password"} helper={signUp ? "At least 8 characters." : undefined} value={values.password} onChange={(e) => setValues({ ...values, password: e.target.value })} required /><Button type="submit" fullWidth loading={pending}>{signUp ? "Create account" : "Sign in"}</Button></form></main></div>;
}
